repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: flake8
