dist: xenial
language: python
jobs:
  include:
    - stage: "Test"
      name: "Test Python 3.6"
      python: "3.6"
      script: pytest
    - stage: "Test"
      name: "Test Python 3.7"
      python: "3.7"
      script: pytest
    - stage: "Code Quality"
      name: "Flake8"
      python: "3.7"
      script: flake8
